import { type CaseRecord, CaseStatus } from '@/types/case';
import { type UserProfile, UserRole } from '@/types/user';
import { type ProcedureRecord } from '@/types/procedure';

// ─── Técnicos / Coordenadores mock ────────────────────────────────────────────

export const MOCK_TECHNICIANS: UserProfile[] = [
  {
    id: 'tech_01',
    name: 'Ana Ferreira',
    email: 'ana.ferreira@creas.gov.br',
    role: UserRole.TECHNICIAN,
    unit: 'CREAS Centro',
    createdAt: '2024-01-10T00:00:00Z',
  },
  {
    id: 'tech_02',
    name: 'Bruno Santos',
    email: 'bruno.santos@creas.gov.br',
    role: UserRole.TECHNICIAN,
    unit: 'CREAS Centro',
    createdAt: '2024-02-05T00:00:00Z',
  },
  {
    id: 'tech_03',
    name: 'Carla Mendes',
    email: 'carla.mendes@creas.gov.br',
    role: UserRole.TECHNICIAN,
    unit: 'CREAS Centro',
    createdAt: '2024-01-20T00:00:00Z',
  },
  {
    id: 'tech_04',
    name: 'Diego Lima',
    email: 'diego.lima@creas.gov.br',
    role: UserRole.TECHNICIAN,
    unit: 'CREAS Centro',
    createdAt: '2024-03-01T00:00:00Z',
  },
  {
    id: 'coord_01',
    name: 'Elaine Costa',
    email: 'elaine.costa@creas.gov.br',
    role: UserRole.COORDINATOR,
    unit: 'CREAS Centro',
    createdAt: '2023-11-15T00:00:00Z',
  },
];

// ─── 20 casos fictícios ────────────────────────────────────────────────────────
// 7 NEW · 9 ACTIVE (6 ok + 3 com alerta de inatividade) · 4 ARCHIVED

export const MOCK_CASES: CaseRecord[] = [
  // ── NEW (7) ────────────────────────────────────────────────────────────────
  {
    id: 'case-01',
    code: 'CAS-2026-0041',
    name: 'Maria da Silva Santos',
    cpf: '324.815.902-67',
    birthDate: '1985-03-12',
    address: 'Rua das Flores, 123',
    neighborhood: 'Centro',
    service: 'PAEFI',
    status: CaseStatus.NEW,
    entryDate: '2026-04-10',
    entryReason: 'violencia_domestica',
    responsibleId: 'tech_01',
    responsibleName: 'Ana Ferreira',
    createdBy: 'tech_01',
    createdAt: '2026-04-10T09:00:00Z',
  },
  {
    id: 'case-02',
    code: 'CAS-2026-0042',
    name: 'João Carlos Ferreira',
    cpf: '193.047.285-31',
    birthDate: '2010-07-22',
    address: 'Av. Brasil, 456',
    neighborhood: 'Vila Operária',
    service: 'SEV',
    status: CaseStatus.NEW,
    entryDate: '2026-04-08',
    entryReason: 'negligencia',
    responsibleId: 'tech_02',
    responsibleName: 'Bruno Santos',
    createdBy: 'tech_02',
    createdAt: '2026-04-08T10:30:00Z',
  },
  {
    id: 'case-03',
    code: 'CAS-2026-0043',
    name: 'Ana Beatriz Oliveira',
    cpf: '758.293.104-85',
    birthDate: '2015-11-05',
    address: 'Rua São Paulo, 789',
    neighborhood: 'Jardim América',
    service: 'SEV',
    status: CaseStatus.NEW,
    entryDate: '2026-04-05',
    entryReason: 'trabalho_infantil',
    responsibleId: 'tech_03',
    responsibleName: 'Carla Mendes',
    createdBy: 'tech_03',
    createdAt: '2026-04-05T08:15:00Z',
  },
  {
    id: 'case-04',
    code: 'CAS-2026-0044',
    name: 'Pedro Henrique Costa',
    cpf: '483.619.027-52',
    birthDate: '1978-09-14',
    address: 'Travessa do Campo, 234',
    neighborhood: 'Bom Retiro',
    service: 'PAEFI',
    status: CaseStatus.NEW,
    entryDate: '2026-04-12',
    entryReason: 'vulnerabilidade_economica',
    responsibleId: 'tech_01',
    responsibleName: 'Ana Ferreira',
    createdBy: 'tech_01',
    createdAt: '2026-04-12T14:00:00Z',
  },
  {
    id: 'case-05',
    code: 'CAS-2026-0045',
    name: 'Fernanda Lima Souza',
    cpf: '267.384.510-93',
    birthDate: '1992-06-30',
    address: 'Rua da Esperança, 567',
    neighborhood: 'Santa Cruz',
    service: 'PAEFI',
    status: CaseStatus.NEW,
    entryDate: '2026-04-03',
    entryReason: 'violencia_psicologica',
    responsibleId: 'tech_04',
    responsibleName: 'Diego Lima',
    createdBy: 'tech_04',
    createdAt: '2026-04-03T11:00:00Z',
  },
  {
    id: 'case-06',
    code: 'CAS-2026-0046',
    name: 'Carlos Eduardo Mendes',
    cpf: '519.072.836-14',
    birthDate: '2008-02-18',
    address: 'Av. das Palmeiras, 890',
    neighborhood: 'Parque das Flores',
    service: 'PAEFI',
    status: CaseStatus.NEW,
    entryDate: '2026-04-01',
    entryReason: 'uso_substancias',
    responsibleId: 'tech_02',
    responsibleName: 'Bruno Santos',
    createdBy: 'tech_02',
    createdAt: '2026-04-01T09:45:00Z',
  },
  {
    id: 'case-07',
    code: 'CAS-2026-0047',
    name: 'Luciana Aparecida Rodrigues',
    cpf: '641.928.370-26',
    birthDate: '1973-04-03',
    address: 'Rua Sete de Setembro, 12',
    neighborhood: 'São José',
    service: 'SEV',
    status: CaseStatus.NEW,
    entryDate: '2026-03-28',
    entryReason: 'situacao_rua',
    responsibleId: 'tech_03',
    responsibleName: 'Carla Mendes',
    createdBy: 'tech_03',
    createdAt: '2026-03-28T10:00:00Z',
  },
  // ── ACTIVE — sem alerta (6) ────────────────────────────────────────────────
  {
    id: 'case-08',
    code: 'CAS-2026-0008',
    name: 'Roberto Carlos Alves',
    cpf: '872.304.519-48',
    birthDate: '1990-12-28',
    address: 'Av. Principal, 345',
    neighborhood: 'Campos Elíseos',
    service: 'PAEFI',
    status: CaseStatus.ACTIVE,
    entryDate: '2026-01-15',
    entryReason: 'violencia_domestica',
    lastReportDate: '2026-04-10',
    responsibleId: 'tech_01',
    responsibleName: 'Ana Ferreira',
    createdBy: 'tech_01',
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'case-09',
    code: 'CAS-2025-0142',
    name: 'Patrícia Gonçalves Silva',
    cpf: '135.790.264-57',
    birthDate: '2012-08-17',
    address: 'Rua Nova, 678',
    neighborhood: 'Nova Esperança',
    service: 'PAEFI',
    status: CaseStatus.ACTIVE,
    entryDate: '2025-11-20',
    entryReason: 'negligencia',
    lastReportDate: '2026-04-05',
    responsibleId: 'tech_04',
    responsibleName: 'Diego Lima',
    createdBy: 'tech_04',
    createdAt: '2025-11-20T08:00:00Z',
  },
  {
    id: 'case-10',
    code: 'CAS-2026-0015',
    name: 'Marcelo Antônio Pereira',
    cpf: '408.571.293-62',
    birthDate: '1982-05-09',
    address: 'Rua Bela Vista, 901',
    neighborhood: 'Bela Vista',
    service: 'SEV',
    status: CaseStatus.ACTIVE,
    entryDate: '2026-02-01',
    entryReason: 'violencia_domestica',
    lastReportDate: '2026-04-08',
    responsibleId: 'tech_02',
    responsibleName: 'Bruno Santos',
    createdBy: 'tech_02',
    createdAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'case-11',
    code: 'CAS-2025-0098',
    name: 'Rosana Maria Cardoso',
    cpf: '962.341.085-70',
    birthDate: '1997-01-25',
    address: 'Rua do Centro, 23',
    neighborhood: 'Centro',
    service: 'PAEFI',
    status: CaseStatus.ACTIVE,
    entryDate: '2025-09-10',
    entryReason: 'violencia_psicologica',
    lastReportDate: '2026-03-28',
    responsibleId: 'tech_03',
    responsibleName: 'Carla Mendes',
    createdBy: 'tech_03',
    createdAt: '2025-09-10T09:00:00Z',
  },
  {
    id: 'case-12',
    code: 'CAS-2026-0003',
    name: 'Eduardo José Nascimento',
    cpf: '374.819.206-33',
    birthDate: '2005-10-14',
    address: 'Av. Operária, 456',
    neighborhood: 'Vila Operária',
    service: 'SEV',
    status: CaseStatus.ACTIVE,
    entryDate: '2026-01-08',
    entryReason: 'uso_substancias',
    lastReportDate: '2026-04-02',
    responsibleId: 'tech_01',
    responsibleName: 'Ana Ferreira',
    createdBy: 'tech_01',
    createdAt: '2026-01-08T11:00:00Z',
  },
  {
    id: 'case-13',
    code: 'CAS-2025-0167',
    name: 'Cristina Paula Barbosa',
    cpf: '829.046.153-94',
    birthDate: '1969-07-31',
    address: 'Rua América, 789',
    neighborhood: 'Jardim América',
    service: 'PAEFI',
    status: CaseStatus.ACTIVE,
    entryDate: '2025-12-05',
    entryReason: 'vulnerabilidade_economica',
    lastReportDate: '2026-04-11',
    responsibleId: 'tech_04',
    responsibleName: 'Diego Lima',
    createdBy: 'tech_04',
    createdAt: '2025-12-05T14:00:00Z',
  },
  // ── ACTIVE — com alerta de inatividade (3) ────────────────────────────────
  {
    id: 'case-14',
    code: 'CAS-2025-0112',
    name: 'Francisco Souza Lima',
    cpf: '153.672.908-45',
    birthDate: '1988-03-22',
    address: 'Tv. do Retiro, 12',
    neighborhood: 'Bom Retiro',
    service: 'PAEFI',
    status: CaseStatus.ACTIVE,
    entryDate: '2025-10-15',
    entryReason: 'violencia_domestica',
    lastReportDate: '2026-02-10',
    responsibleId: 'tech_02',
    responsibleName: 'Bruno Santos',
    createdBy: 'tech_02',
    createdAt: '2025-10-15T09:00:00Z',
  },
  {
    id: 'case-15',
    code: 'CAS-2025-0089',
    name: 'Juliana Cristina Moreira',
    cpf: '706.193.482-18',
    birthDate: '2014-09-06',
    address: 'Rua da Cruz, 345',
    neighborhood: 'Santa Cruz',
    service: 'SEV',
    status: CaseStatus.ACTIVE,
    entryDate: '2025-08-22',
    entryReason: 'trabalho_infantil',
    lastReportDate: '2026-02-28',
    responsibleId: 'tech_03',
    responsibleName: 'Carla Mendes',
    createdBy: 'tech_03',
    createdAt: '2025-08-22T10:00:00Z',
  },
  {
    id: 'case-16',
    code: 'CAS-2026-0020',
    name: 'Antônio Carlos Dias',
    cpf: '241.507.836-99',
    birthDate: '1960-12-15',
    address: 'Av. das Flores, 678',
    neighborhood: 'Parque das Flores',
    service: 'PAEFI',
    status: CaseStatus.ACTIVE,
    entryDate: '2026-01-20',
    entryReason: 'vulnerabilidade_economica',
    lastReportDate: '2026-03-01',
    responsibleId: 'tech_01',
    responsibleName: 'Ana Ferreira',
    createdBy: 'tech_01',
    createdAt: '2026-01-20T09:00:00Z',
  },
  // ── ARCHIVED (4) ──────────────────────────────────────────────────────────
  {
    id: 'case-17',
    code: 'CAS-2025-0055',
    name: 'Sandra Regina Martins',
    cpf: '538.924.071-63',
    birthDate: '1995-04-28',
    address: 'Rua José, 901',
    neighborhood: 'São José',
    service: 'PAEFI',
    status: CaseStatus.ARCHIVED,
    entryDate: '2025-06-01',
    entryReason: 'violencia_psicologica',
    lastReportDate: '2026-03-10',
    archiveDate: '2026-03-15',
    archiveReason: 'objetivo_cumprido',
    archiveNotes: 'Família em situação estável. Objetivos do PAEFI cumpridos com êxito.',
    responsibleId: 'tech_04',
    responsibleName: 'Diego Lima',
    createdBy: 'tech_04',
    createdAt: '2025-06-01T09:00:00Z',
  },
  {
    id: 'case-18',
    code: 'CAS-2025-0063',
    name: 'Leandro Augusto Vieira',
    cpf: '917.283.460-27',
    birthDate: '2003-06-11',
    address: 'Av. Elíseos, 234',
    neighborhood: 'Campos Elíseos',
    service: 'SEV',
    status: CaseStatus.ARCHIVED,
    entryDate: '2025-07-10',
    entryReason: 'uso_substancias',
    lastReportDate: '2026-02-15',
    archiveDate: '2026-02-20',
    archiveReason: 'transferencia',
    archiveNotes: 'Encaminhado para CAPS AD na região norte.',
    responsibleId: 'tech_02',
    responsibleName: 'Bruno Santos',
    createdBy: 'tech_02',
    createdAt: '2025-07-10T10:00:00Z',
  },
  {
    id: 'case-19',
    code: 'CAS-2025-0031',
    name: 'Viviane Ferreira Campos',
    cpf: '394.615.728-81',
    birthDate: '1980-02-07',
    address: 'Rua Esperança, 567',
    neighborhood: 'Nova Esperança',
    service: 'PAEFI',
    status: CaseStatus.ARCHIVED,
    entryDate: '2025-04-15',
    entryReason: 'violencia_domestica',
    archiveDate: '2026-01-30',
    archiveReason: 'abandono',
    archiveNotes: 'Família não compareceu após 3 tentativas de contato em domicílio.',
    responsibleId: 'tech_03',
    responsibleName: 'Carla Mendes',
    createdBy: 'tech_03',
    createdAt: '2025-04-15T09:00:00Z',
  },
  {
    id: 'case-20',
    code: 'CAS-2025-0078',
    name: 'Gabriel Henrique Cruz',
    cpf: '672.048.315-56',
    birthDate: '2018-11-19',
    address: 'Av. Bela, 890',
    neighborhood: 'Bela Vista',
    service: 'SEV',
    status: CaseStatus.ARCHIVED,
    entryDate: '2025-09-05',
    entryReason: 'negligencia',
    archiveDate: '2026-03-01',
    archiveReason: 'mudanca_endereco',
    archiveNotes: 'Família mudou para outro município. Caso encerrado mediante comunicado formal.',
    responsibleId: 'tech_01',
    responsibleName: 'Ana Ferreira',
    createdBy: 'tech_01',
    createdAt: '2025-09-05T11:00:00Z',
  },
];

// ─── Procedimentos mock (linkados por caseId) ─────────────────────────────────

export const MOCK_PROCEDURES: ProcedureRecord[] = [
  {
    id: 'proc-01',
    caseId: 'case-08',
    caseName: 'Roberto Carlos Alves',
    mes: 'Abril',
    ano: 2026,
    servico: 'PAEFI',
    sexo: 'M',
    idade: 35,
    nacionalidade: 'Brasileira',
    data: '2026-04-10',
    instituicao: 'CREAS Centro',
    responsavel: 'Ana Ferreira',
    contatosExito: 2,
    telefonicasSemExito: 1,
    atendimentoIndividualizado: 1,
    atendimentoEmGrupo: 0,
    encaminhamentoCRAS: 0,
    visitasDomiciliar: 1,
    visitasInstitucional: 0,
    visitasSemExito: 0,
    casosDesligados: 0,
    outrosEncaminhamentos: 0,
    reuniaoFamiliar: 1,
    palestras: 0,
    prontuarioSUAS: 1,
    relatorios: 1,
    pias: 0,
    parecer: 0,
    atendidos0a10: 0,
    atendimentos0a10: 0,
    atendidos11a17: 0,
    atendimentos11a17: 0,
    mulheresViolencia: 0,
    outros: 0,
    createdBy: 'tech_01',
    createdAt: '2026-04-10T10:00:00Z',
  },
  {
    id: 'proc-02',
    caseId: 'case-09',
    caseName: 'Patrícia Gonçalves Silva',
    mes: 'Abril',
    ano: 2026,
    servico: 'PAEFI',
    sexo: 'F',
    idade: 13,
    nacionalidade: 'Brasileira',
    data: '2026-04-05',
    instituicao: 'CREAS Centro',
    responsavel: 'Diego Lima',
    contatosExito: 1,
    telefonicasSemExito: 0,
    atendimentoIndividualizado: 1,
    atendimentoEmGrupo: 1,
    encaminhamentoCRAS: 1,
    visitasDomiciliar: 0,
    visitasInstitucional: 0,
    visitasSemExito: 0,
    casosDesligados: 0,
    outrosEncaminhamentos: 1,
    reuniaoFamiliar: 0,
    palestras: 0,
    prontuarioSUAS: 1,
    relatorios: 0,
    pias: 1,
    parecer: 0,
    atendidos0a10: 0,
    atendimentos0a10: 0,
    atendidos11a17: 1,
    atendimentos11a17: 2,
    mulheresViolencia: 0,
    outros: 0,
    createdBy: 'tech_04',
    createdAt: '2026-04-05T09:00:00Z',
  },
  {
    id: 'proc-03',
    caseId: 'case-10',
    caseName: 'Marcelo Antônio Pereira',
    mes: 'Abril',
    ano: 2026,
    servico: 'SEV',
    sexo: 'M',
    idade: 44,
    nacionalidade: 'Brasileira',
    data: '2026-04-08',
    instituicao: 'CREAS Centro',
    responsavel: 'Bruno Santos',
    contatosExito: 3,
    telefonicasSemExito: 0,
    atendimentoIndividualizado: 1,
    atendimentoEmGrupo: 0,
    encaminhamentoCRAS: 0,
    visitasDomiciliar: 1,
    visitasInstitucional: 1,
    visitasSemExito: 0,
    casosDesligados: 0,
    outrosEncaminhamentos: 0,
    reuniaoFamiliar: 1,
    palestras: 0,
    prontuarioSUAS: 1,
    relatorios: 1,
    pias: 0,
    parecer: 1,
    atendidos0a10: 0,
    atendimentos0a10: 0,
    atendidos11a17: 0,
    atendimentos11a17: 0,
    mulheresViolencia: 0,
    outros: 0,
    createdBy: 'tech_02',
    createdAt: '2026-04-08T11:00:00Z',
  },
  {
    id: 'proc-04',
    caseId: 'case-11',
    caseName: 'Rosana Maria Cardoso',
    mes: 'Março',
    ano: 2026,
    servico: 'PAEFI',
    sexo: 'F',
    idade: 29,
    nacionalidade: 'Brasileira',
    data: '2026-03-28',
    instituicao: 'CREAS Centro',
    responsavel: 'Carla Mendes',
    contatosExito: 2,
    telefonicasSemExito: 1,
    atendimentoIndividualizado: 1,
    atendimentoEmGrupo: 1,
    encaminhamentoCRAS: 0,
    visitasDomiciliar: 0,
    visitasInstitucional: 0,
    visitasSemExito: 1,
    casosDesligados: 0,
    outrosEncaminhamentos: 1,
    reuniaoFamiliar: 0,
    palestras: 1,
    prontuarioSUAS: 1,
    relatorios: 1,
    pias: 1,
    parecer: 0,
    atendidos0a10: 0,
    atendimentos0a10: 0,
    atendidos11a17: 0,
    atendimentos11a17: 0,
    mulheresViolencia: 1,
    outros: 0,
    createdBy: 'tech_03',
    createdAt: '2026-03-28T14:00:00Z',
  },
  {
    id: 'proc-05',
    caseId: 'case-12',
    caseName: 'Eduardo José Nascimento',
    mes: 'Abril',
    ano: 2026,
    servico: 'SEV',
    sexo: 'M',
    idade: 20,
    nacionalidade: 'Brasileira',
    data: '2026-04-02',
    instituicao: 'CREAS Centro',
    responsavel: 'Ana Ferreira',
    contatosExito: 1,
    telefonicasSemExito: 2,
    atendimentoIndividualizado: 0,
    atendimentoEmGrupo: 1,
    encaminhamentoCRAS: 0,
    visitasDomiciliar: 0,
    visitasInstitucional: 0,
    visitasSemExito: 0,
    casosDesligados: 0,
    outrosEncaminhamentos: 0,
    reuniaoFamiliar: 0,
    palestras: 1,
    prontuarioSUAS: 0,
    relatorios: 1,
    pias: 0,
    parecer: 0,
    atendidos0a10: 0,
    atendimentos0a10: 0,
    atendidos11a17: 0,
    atendimentos11a17: 0,
    mulheresViolencia: 0,
    outros: 1,
    createdBy: 'tech_01',
    createdAt: '2026-04-02T09:00:00Z',
  },
  {
    id: 'proc-06',
    caseId: 'case-13',
    caseName: 'Cristina Paula Barbosa',
    mes: 'Abril',
    ano: 2026,
    servico: 'PAEFI',
    sexo: 'F',
    idade: 57,
    nacionalidade: 'Brasileira',
    data: '2026-04-11',
    instituicao: 'CREAS Centro',
    responsavel: 'Diego Lima',
    contatosExito: 2,
    telefonicasSemExito: 0,
    atendimentoIndividualizado: 1,
    atendimentoEmGrupo: 1,
    encaminhamentoCRAS: 1,
    visitasDomiciliar: 1,
    visitasInstitucional: 0,
    visitasSemExito: 0,
    casosDesligados: 0,
    outrosEncaminhamentos: 1,
    reuniaoFamiliar: 1,
    palestras: 0,
    prontuarioSUAS: 1,
    relatorios: 1,
    pias: 1,
    parecer: 1,
    atendidos0a10: 0,
    atendimentos0a10: 0,
    atendidos11a17: 0,
    atendimentos11a17: 0,
    mulheresViolencia: 1,
    outros: 0,
    createdBy: 'tech_04',
    createdAt: '2026-04-11T10:00:00Z',
  },
  {
    id: 'proc-07',
    caseId: 'case-09',
    caseName: 'Patrícia Gonçalves Silva',
    mes: 'Março',
    ano: 2026,
    servico: 'PAEFI',
    sexo: 'F',
    idade: 13,
    nacionalidade: 'Brasileira',
    data: '2026-03-15',
    instituicao: 'CREAS Centro',
    responsavel: 'Diego Lima',
    contatosExito: 1,
    telefonicasSemExito: 0,
    atendimentoIndividualizado: 1,
    atendimentoEmGrupo: 0,
    encaminhamentoCRAS: 0,
    visitasDomiciliar: 1,
    visitasInstitucional: 0,
    visitasSemExito: 0,
    casosDesligados: 0,
    outrosEncaminhamentos: 0,
    reuniaoFamiliar: 1,
    palestras: 0,
    prontuarioSUAS: 0,
    relatorios: 1,
    pias: 0,
    parecer: 0,
    atendidos0a10: 0,
    atendimentos0a10: 0,
    atendidos11a17: 1,
    atendimentos11a17: 1,
    mulheresViolencia: 0,
    outros: 0,
    createdBy: 'tech_04',
    createdAt: '2026-03-15T09:00:00Z',
  },
  {
    id: 'proc-08',
    caseId: 'case-08',
    caseName: 'Roberto Carlos Alves',
    mes: 'Março',
    ano: 2026,
    servico: 'PAEFI',
    sexo: 'M',
    idade: 35,
    nacionalidade: 'Brasileira',
    data: '2026-03-20',
    instituicao: 'CREAS Centro',
    responsavel: 'Ana Ferreira',
    contatosExito: 1,
    telefonicasSemExito: 1,
    atendimentoIndividualizado: 1,
    atendimentoEmGrupo: 0,
    encaminhamentoCRAS: 0,
    visitasDomiciliar: 0,
    visitasInstitucional: 0,
    visitasSemExito: 1,
    casosDesligados: 0,
    outrosEncaminhamentos: 0,
    reuniaoFamiliar: 0,
    palestras: 0,
    prontuarioSUAS: 1,
    relatorios: 1,
    pias: 0,
    parecer: 0,
    atendidos0a10: 0,
    atendimentos0a10: 0,
    atendidos11a17: 0,
    atendimentos11a17: 0,
    mulheresViolencia: 0,
    outros: 0,
    createdBy: 'tech_01',
    createdAt: '2026-03-20T10:00:00Z',
  },
];
